import { Roboto } from "next/font/google";

import Providers from "./providers";

import "./globals.scss";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="uk" className={roboto.variable}>
      <body className={`${roboto.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
